---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    pacman:
      update_cache: yes

  - name: install apache2 package
    pacman: 
      name: apache
      state: latest

  - name: install php support for apache
    pacman:
      name: php-apache
      state: latest
